[package]
name = "aporia-standalone"
version = "0.0.1"
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
unsafe-pool = { version = "0.0.1", path = "../unsafe-pool" }
aporia-core = { version = "0.0.1", path = "../aporia-core" }
winit = { version = "0.30.13" }
wgpu = { version = "30.0.1" }
pollster = { version = "1.0.1" }
bytemuck = { version = "1.25.2" }

[dev-dependencies]
env_logger = { version = "0.11.11" }
aporia-std = { version = "0.0.1", path = "../aporia-std" }

[[example]]
name = "counter"
path = "examples/counter/main.rs"
